### ISSUE TITLE
Roster Images fail to load

### ISSUE THREAD

**Issue by spitefultowel** [bbDKP/bbGuild#266]
Attempting to view the roster and images aren't showing. Opening the image in a new tab gives the following as an example.

`No route found for "GET /guild/ext/bbdkp/bbguild/images/race_images/wow_pandaren_female.png"`

**Comment by Sajaki** [comment]
it's fixed now.

**Comment by spitefultowel** [comment]
Just downloaded the latest file and put it into ext/bbdkp/bbguild/controller and images still don't show.

**Comment by Tankyspanky** [comment]
Mine are working World of Warcraft Game

**Comment by spitefultowel** [comment]
Downloading latest tarball worked.
